name: Backend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
        
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      

      - name: Run Flask app (check startup)
        env:
          FLASK_APP: run.py
          FLASK_ENV: DevelopmentConfig
          DATABASE_URL: "sqlite:///:memory:"
          JWT_SECRET_KEY: "${{ secrets.JWT_SECRET_KEY }}"
        run: |
          python -m flask run --no-debugger --no-reload &
          sleep 10
          curl http://127.0.0.1:5000 || (echo "Flask app did not start!" && exit 1)

    #   - name: Lint with flake8
    #     run: |
    #       pip install flake8
    #       flake8 app

      # Uncomment and adapt if you add tests
      # - name: Run tests
      #   run: |
      #     pip install pytest
      #     pytest