name: Build and Push to ACR

on:
  push:
    branches:
      - main
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Log in to ACR
      uses: azure/docker-login@v1
      with:
        login-server: lien mta3 registre
        username: ${{ secrets.Azure_Creds.Azure_USERNAME }}
        password: ${{ secrets.Azure_Creds.Azure_PASSWORD }}
  build-frontend:
    runs-on: ubuntu-latest
    needs: login
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Frontend Docker image
      run: |
        docker build -t esmacr.azurecr.io/frontend ./frontend
  push-frontend:

